# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-20 00:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthCache',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField()),
                ('data_cache', models.TextField()),
                ('data_cached_on', models.DateTimeField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='calendar',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='monthcache',
            name='calendar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Calendar'),
        ),
    ]
