# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-27 19:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20161019_1612'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calendar',
            name='css_class',
        ),
        migrations.AddField(
            model_name='calendar',
            name='style_bgcolor',
            field=models.CharField(default='white', max_length=20),
        ),
        migrations.AddField(
            model_name='calendar',
            name='style_textcolor',
            field=models.CharField(default='black', max_length=20),
        ),
    ]
