# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-20 01:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='board',
            options={'ordering': ('slug',)},
        ),
    ]
