# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-06 21:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_auto_20171004_1144'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoardCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25)),
            ],
        ),
        migrations.RemoveField(
            model_name='board',
            name='parent',
        ),
        migrations.AddField(
            model_name='board',
            name='category',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='boards', to='forum.BoardCategory'),
        ),
    ]
