# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-06 21:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_auto_20171006_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='boards', to='forum.BoardCategory'),
        ),
    ]
