# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-12 17:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import forum.models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0006_auto_20171007_1425'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='board',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='posts', to='forum.Board'),
        ),
        migrations.AddField(
            model_name='post',
            name='op',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='posts', to='forum.Post'),
        ),
        migrations.AlterField(
            model_name='post',
            name='body',
            field=forum.models.MarkdownField(blank=True, help_text='We use a slightly-customized version of <a data-toggle="modal" data-target="#MarkdownHelp">Markdown</a> for formatting.'),
        ),
    ]
