# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-12 17:58
from __future__ import unicode_literals

from django.db import migrations


def migrate_ops(apps, schema_editor):
    Post = apps.get_model('forum', 'Post')

    ops = {}
    for p in Post.objects.all():
        try:
            op = ops[p.topic_id]
        except KeyError:
            ops[p.topic_id] = Post.objects.filter(topic_id=p.topic_id).first()
            op = ops[p.topic_id]

        p.op = op
        p.board = p.topic.board

        p.save()


def reverse(apps, schema_editor):
    Post = apps.get_model('forum', 'Post')

    for p in Post.objects.all():
        p.op = None
        p.board = None

        p.save()


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0007_auto_20171012_0958'),
    ]

    operations = [
            migrations.RunPython(migrate_ops, reverse)
    ]
