# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-12 19:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0009_auto_20171012_1124'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='board',
        ),
        migrations.DeleteModel(
            name='Topic',
        ),
    ]
