# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-18 00:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import forum.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forum', '0010_auto_20171012_1129'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='readers',
            field=models.ManyToManyField(related_name='read_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='body',
            field=forum.models.MarkdownField(blank=True, help_text='<a data-toggle="modal" data-target="#MarkdownHelp"><span class="octicon octicon-markdown"></span> Markdown</a> will be used to format your post.'),
        ),
    ]
