# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-05 22:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import passwordless.utils


class Migration(migrations.Migration):

    dependencies = [
        ('passwordless', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppPassword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(default=passwordless.utils.new_app_password, max_length=80)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_used', models.DateTimeField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='passwordless.User')),
            ],
        ),
    ]
