# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-30 19:38
from __future__ import unicode_literals

from django.db import migrations, models
import passwordless.models


class Migration(migrations.Migration):

    dependencies = [
        ('passwordless', '0002_user_last_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='authtoken',
            name='session_key',
            field=models.CharField(default=passwordless.models.make_token, max_length=40),
        ),
        migrations.AlterField(
            model_name='authtoken',
            name='token',
            field=models.CharField(default=passwordless.models.make_token, max_length=40, unique=True),
        ),
    ]
