# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-06 17:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passwordless', '0002_apppassword'),
    ]

    operations = [
        migrations.AddField(
            model_name='apppassword',
            name='name',
            field=models.CharField(default='App Password', max_length=30),
            preserve_default=False,
        ),
    ]
