# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-31 22:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passwordless', '0004_auto_20161013_0915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(editable=False, null=True),
        ),
    ]
