# Generated by Django 2.2.6 on 2019-11-11 18:14

from django.db import migrations


def clear_passwords(apps, schema_editor):
    AppPassword = apps.get_model('passwordless', 'AppPassword')

    AppPassword.objects.all().delete()


def unmigrate(apps, schema_editor):
    # Can't put them back...
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('passwordless', '0005_auto_20161031_1422'),
    ]

    operations = [
        migrations.RunPython(clear_passwords, unmigrate),
    ]
