# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-11 19:21
from __future__ import unicode_literals

from django.db import migrations, models
import prosody.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prosody',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.TextField(default=prosody.utils.getProsodyDomain)),
                ('user', models.TextField(db_index=True)),
                ('store', models.TextField(db_index=True)),
                ('key', models.TextField(db_index=True)),
                ('type', models.TextField(default='string')),
                ('value', models.TextField()),
            ],
            options={
                'db_table': 'prosody',
            },
        ),
        migrations.AlterUniqueTogether(
            name='prosody',
            unique_together=set([('user', 'store', 'key')]),
        ),
    ]
