# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-30 02:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='characternotesanswer',
            name='question',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tools.CharacterNotes'),
            preserve_default=False,
        ),
    ]
