# Generated by Django 2.2.6 on 2019-11-13 17:51

from django.db import migrations


def create_default_stories(apps, schema_editor):
    Story = apps.get_model('tools', 'Story')
    Character = apps.get_model('tools', 'Character')

    for c in Character.objects.values('owner').distinct():
        owner_id = c['owner']

        story = Story(title='Untitled', owner_id=owner_id)
        story.save()

        Character.objects.filter(owner_id=owner_id).update(story=story)


def remove_default_stories(apps, schema_editor):
    Story = apps.get_model('tools', 'Story')
    Character = apps.get_model('tools', 'Character')

    Character.objects.update(story=None)
    Story.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0004_auto_20191113_0851'),
    ]

    operations = [
        migrations.RunPython(create_default_stories, remove_default_stories),
    ]
