# Generated by Django 2.2.6 on 2019-11-13 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0005_create_default_stories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='story',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tools.Story'),
        ),
    ]
